- name: Install and build Dockerfile
  hosts: localhost
  become: true
  tasks:
    - name: Copy Dockerfile to the project directory
      copy:
        src: Dockerfile
        dest: /home/berja/HOA11
        owner: berja
        group: berja
        mode: '0755'

    - name: Build Docker image
      shell:
        cmd: "docker build -t berja /home/berja/HOA11"
