- name: Install and build Dockerfile
  hosts: localhost
  become: true
  tasks:
    -   name: Copy Dockerfile to the project directory
        copy:
          src: Dockerfile
          dest: /home/leis/HOA11
          owner: leis
          group: leis
          mode: '0755'

    - name: Build Docker image
        shell:
          cmd: "docker build -t leis /home/leis/HOA11"
